# Generated by Django 5.2.8 on 2025-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberScamStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('direct_trade', models.IntegerField()),
                ('shopping_mall', models.IntegerField()),
                ('game', models.IntegerField()),
                ('email_trade', models.IntegerField()),
                ('romance', models.IntegerField()),
                ('investment', models.IntegerField()),
                ('etc', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TravelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('departures', models.IntegerField(help_text='출국자 수')),
                ('ratio', models.FloatField(blank=True, help_text='전년 대비 증감률(%)', null=True)),
            ],
            options={
                'ordering': ['year', 'month', 'region', 'country'],
                'unique_together': {('region', 'country', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='VoicePhishingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('cases', models.IntegerField()),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
